---
title: "R Blogging in the Cloud"
author: "Seth Dobson"
date: "5/25/2020"
output:
  md_document:
    variant: markdown_github
---

Setting up an R blog on GitHub Pages with Jekyll and RStudio Cloud

## Introduction

Let's face it. Can you really call yourself a member of the #rstats community if you don't have your own blog where you share cool stuff about R? Sure. But many R users and developers blog regularly about R, and many of them use the package [blogdown](https://bookdown.org/yihui/blogdown/) to do it.

Blogdown is awesome. It helps you create really nice looking personal websites based on [R Markdown](https://rmarkdown.rstudio.com/). And with RStudio’s built-in blogdown package support, creating a new blog is as easy as `File -> New Project -> New Directory -> Website` once blogdown and [Hugo](https://gohugo.io/) are installed locally.

Here's my problem. I prefer to use a Chromebook for my recreational data science, which means I work almost exclusively in [RStudio Cloud]((https://rstudio.cloud). So for me, blogdown is not a viable option. Blogdown requires you to download Hugo and build your site locally, which kind of defeats the purpose of a Chromebook in my opinion. I'd rather do everything in the cloud if possible, and as easily as possible.

Fortunately, RStudio Cloud has excellent integration with GitHub, and GitHub Pages lets you create a blog directly from a  repository with Jekyll. Like Hugo, Jekyll is a static website generator. The advantage of Jekyll for Chromebook and/or RStudio Cloud users is that setting up a blog is as easy as forking a repository (see below). With Jekyll, there is no need to download anything, or to build the site locally before deploying it GitHub Pages.

In this post, I will describe how to set up a blog on GitHub Pages using Jekyll and RStudio Cloud.

## Getting Started

Barry Clark has written an excellent tutorial entitled [Build A Blog With Jekyll And GitHub Pages](https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/) that you should read. In this section, I will briefly summarize some of the main points of the tutorial. I will assume you already have a GitHub account. 

The first step in building your own site is to go to the [Jekyll Now](https://github.com/barryclark/jekyll-now) repository and click `fork` in the upper right hand corner. Now you have an exact copy of the repo on your GitHub account.

Next, simply rename the forked repository as [yourusername].github.io and presto! GitHub Pages will build a site using the Jekyll Now theme, and host it for free at the aformentioned URL. It's just that simple.

At this point, you will want to customize your site's appearance a bit by making changes to the `_config.yml` file in the master branch of the repo. This is where you can give your site a name and a brief description. You can also add an avatar, and social links that will appear at the bottom of your site. 

Lastly, you should update the `about.md` file in the master branch if you want to have an "About Me" page on your blog.

After following these simple steps to set up your blog, you're ready to connect to RStudio Cloud and start writing posts.

## Writing in RStudio Cloud

### Connect to repository

### Create RMarkdown file

### Knit to Markdown

## Publishing on GitHub Pages

### Committ and Push Changes

### Last but not least

## Conclusion